# Generated by Django 5.0.8 on 2026-02-13

import hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_slug", models.SlugField(max_length=120)),
                ("lesson_slug", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, default="", max_length=300)),
                ("source_url", models.URLField(blank=True, default="")),
                ("video_file", models.FileField(blank=True, null=True, upload_to=hub.models._lesson_video_upload_to)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order_index", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="lessonvideo",
            index=models.Index(fields=["course_slug", "lesson_slug", "is_active"], name="hub_lessonv_course__be98cb_idx"),
        ),
    ]
