# Generated by Django 5.0.8 on 2026-02-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_lessonvideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_slug", models.SlugField(max_length=120)),
                ("lesson_slug", models.SlugField(max_length=120)),
                ("available_on", models.DateField(blank=True, null=True)),
                ("force_locked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_releases",
                        to="hub.class",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="lessonrelease",
            constraint=models.UniqueConstraint(
                fields=("classroom", "course_slug", "lesson_slug"),
                name="uniq_lesson_release_per_class_lesson",
            ),
        ),
        migrations.AddIndex(
            model_name="lessonrelease",
            index=models.Index(
                fields=["classroom", "course_slug", "lesson_slug"],
                name="hub_lessonr_classro_0a0884_idx",
            ),
        ),
    ]
