# Generated by Django 5.0.8 on 2026-02-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0006_auditevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("class_join", "Class join"),
                            ("session_rejoin_device_hint", "Session rejoin (device hint)"),
                            ("session_rejoin_return_code", "Session rejoin (return code)"),
                            ("submission_upload", "Submission upload"),
                            ("helper_chat_access", "Helper chat access"),
                        ],
                        max_length=48,
                    ),
                ),
                ("source", models.CharField(default="classhub", max_length=40)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_events",
                        to="hub.class",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="hub.studentidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="studentevent",
            index=models.Index(fields=["event_type", "created_at"], name="hub_studente_event_t_e17920_idx"),
        ),
        migrations.AddIndex(
            model_name="studentevent",
            index=models.Index(fields=["classroom", "created_at"], name="hub_studente_classro_d3d6f9_idx"),
        ),
        migrations.AddIndex(
            model_name="studentevent",
            index=models.Index(fields=["student", "created_at"], name="hub_studente_student_43a607_idx"),
        ),
    ]
